// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
)

const getUserDbId = `-- name: GetUserDbId :one
SELECT db_id FROM users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserDbId(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, getUserDbId, userID)
	var db_id int64
	err := row.Scan(&db_id)
	return db_id, err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (user_id, legacy_sync_code) VALUES ($1, $2) RETURNING db_id
`

type InsertUserParams struct {
	UserID         string
	LegacySyncCode string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser, arg.UserID, arg.LegacySyncCode)
	return err
}

const selectAllUsers = `-- name: SelectAllUsers :many
SELECT db_id, user_id
FROM users
`

type SelectAllUsersRow struct {
	DbID   int64
	UserID string
}

func (q *Queries) SelectAllUsers(ctx context.Context) ([]SelectAllUsersRow, error) {
	rows, err := q.db.Query(ctx, selectAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectAllUsersRow
	for rows.Next() {
		var i SelectAllUsersRow
		if err := rows.Scan(&i.DbID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserDbId = `-- name: SelectUserDbId :one
SELECT db_id FROM users WHERE user_id = $1 LIMIT 1
`

func (q *Queries) SelectUserDbId(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, selectUserDbId, userID)
	var db_id int64
	err := row.Scan(&db_id)
	return db_id, err
}

const selectUserDbIdBySyncCode = `-- name: SelectUserDbIdBySyncCode :one
SELECT db_id FROM users WHERE legacy_sync_code = $1 LIMIT 1
`

func (q *Queries) SelectUserDbIdBySyncCode(ctx context.Context, legacySyncCode string) (int64, error) {
	row := q.db.QueryRow(ctx, selectUserDbIdBySyncCode, legacySyncCode)
	var db_id int64
	err := row.Scan(&db_id)
	return db_id, err
}
